name: MenottePlugin
main: ch.m4th1eu.handcuffs.Main
version: 1.0.0
author: M4TH1EU - mathieubroillet.ch
commands:
   mn:
      description: Base de toutes les commandes.
      aliases: hc
      usage: ยง6[Menottes] ยงa Usage : /mn [transport - menotte - libere] [nom du joueur]